language: python
install:
  - pip install -r requirements.txt
deploy:
  provider: heroku
  buildpack: python
  api_key:
    secure: 77efd634-3147-464a-8c9d-cacb20c09140
  app: cincodigo
  on:
    repo: guidofranco/cincodigo-django
before_script:
  - python manage.py collectstatic
script:
  - python manage.py test
notifications:
  slack: cincodigo:Hib7R9oN4qvOQ3y0PoBMbKLZ